/**
 * Generates the public TypeScript declarations and the C binding ABI header from the catalog.
 *
 * Generation adapts names and shapes. It implements no algorithm and reads no reference
 * declaration: `api/catalog.json` is the contract, and everything below is spelling.
 *
 *   pnpm --filter @threenative/three-native generate
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  type CatalogEntry,
  type ICatalog,
  type ICatalogClassEntry,
  type ICatalogField,
  type ICatalogMethod,
  type ICatalogParameter,
  TN_CAPABILITY_DIGEST_PREFIX,
  capabilityDigest,
  loadCatalog,
  supportedNativeSymbols,
} from "../src/catalog.js";

const ROOT = path.resolve(import.meta.dirname, "..", "..", "..");
const DECLARATIONS = path.join(ROOT, "packages", "three-native", "generated", "three.d.ts");
const HEADER = path.join(
  ROOT,
  "packages",
  "runtime-native",
  "include",
  "threenative",
  "abi",
  "tn_abi.h",
);

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/u;
const RESERVED = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "static",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
]);

/** A member named `static` or `default` is legal as a property only when quoted. */
function memberName(name: string): string {
  return IDENTIFIER.test(name) && !RESERVED.has(name) ? name : JSON.stringify(name);
}

function isPublished(entry: CatalogEntry): boolean {
  return entry.status.kind !== "unsupported";
}

function parameter(parameter: ICatalogParameter): string {
  const prefix = parameter.rest === true ? "..." : "";
  const suffix = parameter.optional ? "?" : "";
  return `${prefix}${memberName(parameter.name)}${suffix}: ${parameter.type}`;
}

function fieldLine(field: ICatalogField): string {
  return `${field.mutable ? "" : "readonly "}${memberName(field.name)}: ${field.type};`;
}

function statusLabel(entry: CatalogEntry): string {
  if (entry.status.kind === "partial") return `partial (${entry.status.gaps.join(", ")})`;
  if (entry.status.kind === "unsupported") return `unsupported (${entry.status.diagnostic})`;
  return "supported";
}

/** Callback parameters become a doc tag; the signature itself is the parameter's type. */
function callbackTag(method: ICatalogMethod): string {
  const callbacks = (method.overloads[0]?.parameters ?? [])
    .filter((parameter) => parameter.callback !== undefined)
    .map((parameter) => `${parameter.name}: ${parameter.callback}`);
  return callbacks.length === 0 ? "" : `/** callback ${callbacks.join(", ")} */\n`;
}

function classDeclaration(entry: ICatalogClassEntry): string[] {
  const body: string[] = [`constructor(${entry.constructor.map(parameter).join(", ")});`];
  for (const field of entry.fields) {
    if (field.status?.kind === "unsupported") continue;
    body.push(fieldLine(field));
  }
  for (const method of entry.methods) {
    if (method.status?.kind === "unsupported") continue;
    body.push(
      `  ${callbackTag(method)}`.trimEnd(),
      ...method.overloads.map(
        (overload) =>
          `  ${memberName(method.name)}(${overload.parameters.map(parameter).join(", ")}): ${overload.returns};`,
      ),
    );
  }
  return [
    `export declare class ${entry.name}${entry.extends === null ? "" : ` extends ${entry.extends}`} {`,
    ...body,
    "}",
  ];
}

function declaration(entry: CatalogEntry): string[] {
  const lines = [`/** Catalog ${statusLabel(entry)}: ${entry.source}/${entry.name}. */`];
  if (entry.status.kind === "unsupported")
    return [
      ...lines,
      `export declare const ${entry.name}: IUnsupportedCatalogSymbol<"${entry.name}">;`,
    ];
  if (entry.kind === "constant")
    return [...lines, `export declare const ${entry.name}: ${entry.value};`];
  if (entry.kind === "enum")
    return [
      ...lines,
      `export declare const ${entry.name} = {`,
      ...entry.values.map((value) => `  ${memberName(value.name)}: ${value.value},`),
      "} as const;",
      `export type ${entry.name} = (typeof ${entry.name})[keyof typeof ${entry.name}];`,
    ];
  if (entry.kind === "type") return [...lines, `export type ${entry.name} = ${entry.type};`];
  if (entry.kind === "function")
    return [
      ...lines,
      `export declare function ${entry.name}(${(entry.parameters ?? []).map(parameter).join(", ")}): ${entry.returns ?? "void"};`,
    ];
  return [...lines, ...classDeclaration(entry)];
}

function declarations(catalog: ICatalog): string {
  return [
    "// Generated by @threenative/three-native from api/catalog.json. Do not edit.",
    "// An unsupported entry is a compile-time trap carrying its diagnostic code.",
    "",
    "export interface IUnsupportedCatalogSymbol<Name extends string> {",
    "  readonly unsupported: Name;",
    "  new (...arguments_: never[]): never;",
    "}",
    "",
    ...catalog.entries.filter(isPublished).flatMap((entry) => [...declaration(entry), ""]),
  ].join("\n");
}

/**
 * Status codes. The number is the wire contract: a module compiled against TN_ERROR_STALE_HANDLE 3u
 * keeps meaning it, so a new code appends and no value is renumbered or reused.
 */
const STATUS_CODES: readonly (readonly [name: string, value: number, doc: string])[] = [
  ["TN_OK", 0, "The call succeeded and carries no diagnostic."],
  ["TN_ERROR_INVALID_ARGUMENT", 1, "A descriptor, length, stride or scalar type was not usable."],
  ["TN_ERROR_INVALID_HANDLE", 2, "The handle's type, context or generation did not resolve."],
  ["TN_ERROR_STALE_HANDLE", 3, "The slot was reclaimed and its generation no longer matches."],
  ["TN_ERROR_WRONG_TYPE", 4, "The handle resolved to a different catalog type."],
  ["TN_ERROR_OUT_OF_MEMORY", 5, "The engine could not satisfy the request."],
  [
    "TN_ERROR_UNSUPPORTED",
    6,
    "The catalog marks this operation unsupported; see its diagnostic code.",
  ],
  [
    "TN_ERROR_VERSION_MISMATCH",
    7,
    "A version number or the capability digest is not the engine's own.",
  ],
  ["TN_ERROR_INVALID_STATE", 8, "The object is not in a state where the call is defined."],
  ["TN_ERROR_BUFFER_NOT_READY", 9, "The buffer is still owned by the engine for this submission."],
];

/** Scalar types, buffer owners and mutability. Also `uint32_t` typedefs, never C enums. */
const SCALAR_TYPES: readonly (readonly [name: string, value: number, doc: string])[] = [
  ["TN_SCALAR_F32", 0, "IEEE-754 binary32."],
  ["TN_SCALAR_I32", 1, "Signed 32-bit integer."],
  ["TN_SCALAR_U32", 2, "Unsigned 32-bit integer."],
  ["TN_SCALAR_U8", 3, "Unsigned 8-bit integer."],
  ["TN_SCALAR_U16", 4, "Unsigned 16-bit integer."],
  ["TN_SCALAR_I16", 5, "Signed 16-bit integer."],
];

const BUFFER_OWNERS: readonly (readonly [name: string, value: number, doc: string])[] = [
  ["TN_BUFFER_OWNER_ENGINE", 0, "The engine owns the storage for the lifetime of the lease."],
  [
    "TN_BUFFER_OWNER_CALLER",
    1,
    "The caller owns the storage and keeps it alive until the engine is done with it.",
  ],
];

const BUFFER_MUTABILITIES: readonly (readonly [name: string, value: number, doc: string])[] = [
  ["TN_BUFFER_READ_ONLY", 0, "The engine only reads through the descriptor."],
  ["TN_BUFFER_READ_WRITE", 1, "The engine writes through the descriptor."],
];

/** The named reasons a handshake fails, so a rejected module says which field disagreed. */
const VERSION_DIAGNOSTICS: readonly (readonly [name: string, value: number, doc: string])[] = [
  ["TN_DIAG_ENGINE_ABI_MISMATCH", 1001, "engine_abi differs from the engine's own."],
  ["TN_DIAG_CONTRACT_MISMATCH", 1002, "compatibility_contract differs from the engine's own."],
  ["TN_DIAG_SCENE_MISMATCH", 1003, "scene differs from the engine's own."],
  ["TN_DIAG_SHADER_PACKAGE_MISMATCH", 1004, "shader_package differs from the engine's own."],
  [
    "TN_DIAG_CAPABILITY_MISMATCH",
    1005,
    "capability_count or capability_digest differs from the engine's own.",
  ],
];

function codeBlock(codes: readonly (readonly [string, number, string])[]): string {
  return codes.map(([name, value, doc]) => `#define ${name} ${value}u /* ${doc} */`).join("\n");
}

function header(catalog: ICatalog): string {
  const { abi } = catalog;
  const digest = capabilityDigest(catalog);
  const supported = supportedNativeSymbols(catalog).length;
  return `/* Generated by @threenative/three-native from api/catalog.json. Do not edit.
 *
 * The binding boundary of the N03 catalog: fixed-width fields, opaque typed handles, explicit
 * buffer descriptors, callback-plus-context pairs, status codes and owned diagnostic strings. No
 * STL container and no C++ exception crosses it.
 *
 * Every code is a \`#define\` over a \`uint32_t\` typedef, never a C enum: an enum's width is the
 * compiler's choice, so its size would not be part of the contract. Values are never renumbered or
 * reused; new codes append. \`TN_STATIC_ASSERT\` is \`_Static_assert\` in C and \`static_assert\` in
 * C++, so every translation unit that includes this header checks the layout below.
 *
 * Reference: three ${catalog.reference.three}, ${catalog.reference.types},
 * patch ${catalog.reference.patch}.
 */

#ifndef THREENATIVE_ABI_TN_ABI_H
#define THREENATIVE_ABI_TN_ABI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Linkage annotation; a single-translation-unit build needs none. */
#ifndef TN_EXPORT
#define TN_EXPORT
#endif

#ifdef __cplusplus
#define TN_STATIC_ASSERT(condition, message) static_assert(condition, message)
#else
#define TN_STATIC_ASSERT(condition, message) _Static_assert(condition, message)
#endif

#define TN_ENGINE_ABI_VERSION ${abi.engine}u
#define TN_COMPATIBILITY_CONTRACT_VERSION ${abi.compatibilityContract}u
#define TN_SCENE_VERSION ${abi.scene}u
#define TN_SHADER_PACKAGE_VERSION ${abi.shaderPackage}u

/* FNV-1a 64 over the UTF-8 bytes of the text "${TN_CAPABILITY_DIGEST_PREFIX}" followed by the names
 * of the catalog entries with status \`supported\`, sorted by code unit and joined with a single
 * newline, with no trailing newline. A module built against a different published surface hashes
 * differently, which is what TN_DIAG_CAPABILITY_MISMATCH reports. */
#define TN_CAPABILITY_DIGEST 0x${digest.toString(16)}ull
#define TN_CAPABILITY_COUNT ${supported}u

typedef uint32_t tn_status_t;

${codeBlock(STATUS_CODES)}

/* The named reasons a version handshake failed, carried in tn_diagnostic_t::code while the status
 * stays TN_ERROR_VERSION_MISMATCH. New codes append. */
${codeBlock(VERSION_DIAGNOSTICS)}

/* An opaque typed handle. \`context\` separates independent handle tables and \`generation\` catches a
 * reclaimed slot, so a stale handle returns a status code instead of aliasing live state. */
typedef struct tn_handle {
  uint16_t type;
  uint16_t context;
  uint32_t index;
  uint32_t generation;
} tn_handle_t;

TN_STATIC_ASSERT(sizeof(tn_handle_t) == 12, "tn_handle_t must stay 12 bytes: 2 + 2 + 4 + 4.");
TN_STATIC_ASSERT(offsetof(tn_handle_t, type) == 0 && offsetof(tn_handle_t, context) == 2 &&
                     offsetof(tn_handle_t, index) == 4 && offsetof(tn_handle_t, generation) == 8,
                 "tn_handle_t must keep this field order and no padding holes.");

/* A diagnostic the caller owns: release it with tn_diagnostic_release, never with free(). Pass a
 * zeroed struct the first time; every call that takes one releases the message it held before
 * writing, so one diagnostic can be reused across calls without leaking. */
typedef struct tn_diagnostic {
  char *message;
  uint32_t code;
} tn_diagnostic_t;

typedef uint32_t tn_scalar_type_t;

${codeBlock(SCALAR_TYPES)}

typedef uint32_t tn_buffer_owner_t;

${codeBlock(BUFFER_OWNERS)}

typedef uint32_t tn_buffer_mutability_t;

${codeBlock(BUFFER_MUTABILITIES)}

/* Every buffer crossing the ABI states its owner, length, stride, scalar type and mutability.
 * Ownership and lease rules are PRD-504; \`length\` counts elements, never bytes. */
typedef struct tn_buffer_desc {
  void *data;
  uint64_t length;
  uint64_t stride;
  tn_scalar_type_t scalar_type;
  tn_buffer_owner_t owner;
  tn_buffer_mutability_t mutability;
  /* Bumped by the engine on every write, so a retained view can prove it is current. */
  uint32_t version;
} tn_buffer_desc_t;

TN_STATIC_ASSERT(sizeof(tn_buffer_desc_t) == 40,
                 "tn_buffer_desc_t must stay 40 bytes: 8 + 8 + 8 + 4 + 4 + 4 + 4.");
TN_STATIC_ASSERT(offsetof(tn_buffer_desc_t, data) == 0 && offsetof(tn_buffer_desc_t, length) == 8 &&
                     offsetof(tn_buffer_desc_t, stride) == 16 &&
                     offsetof(tn_buffer_desc_t, scalar_type) == 24 &&
                     offsetof(tn_buffer_desc_t, owner) == 28 &&
                     offsetof(tn_buffer_desc_t, mutability) == 32 &&
                     offsetof(tn_buffer_desc_t, version) == 36,
                 "tn_buffer_desc_t must keep this field order and no padding holes.");

/* A callback plus the context it runs with. The pair crosses as one value; a bare function pointer
 * would lose the wrapper that owns the capture. */
typedef void (*tn_callback_t)(void *context, const tn_diagnostic_t *diagnostic);

/* The 64-bit digest comes first so nothing precedes it, and \`reserved\` names the four tail bytes
 * the 8-byte alignment would otherwise insert: the struct has no implicit padding. */
typedef struct tn_version_info {
  uint64_t capability_digest;
  uint32_t engine_abi;
  uint32_t compatibility_contract;
  uint32_t scene;
  uint32_t shader_package;
  uint32_t capability_count;
  uint32_t reserved;
} tn_version_info_t;

TN_STATIC_ASSERT(sizeof(tn_version_info_t) == 32,
                 "tn_version_info_t must stay 32 bytes: 8 + 4 + 4 + 4 + 4 + 4 + 4.");
TN_STATIC_ASSERT(offsetof(tn_version_info_t, capability_digest) == 0 &&
                     offsetof(tn_version_info_t, engine_abi) == 8 &&
                     offsetof(tn_version_info_t, compatibility_contract) == 12 &&
                     offsetof(tn_version_info_t, scene) == 16 &&
                     offsetof(tn_version_info_t, shader_package) == 20 &&
                     offsetof(tn_version_info_t, capability_count) == 24 &&
                     offsetof(tn_version_info_t, reserved) == 28,
                 "tn_version_info_t must keep this field order and no padding holes.");

typedef struct tn_context tn_context_t;

/* The engine's own versions, capability count and capability digest. */
TN_EXPORT tn_version_info_t tn_engine_version(void);

/* Rejects a module built against a different engine ABI, compatibility contract, scene, shader
 * package or capability set before any game code runs. On mismatch it returns
 * TN_ERROR_VERSION_MISMATCH, fills \`engine\` when it is non-NULL, and sets \`diagnostic->code\` to the
 * first differing field in this order: TN_DIAG_ENGINE_ABI_MISMATCH, TN_DIAG_CONTRACT_MISMATCH,
 * TN_DIAG_SCENE_MISMATCH, TN_DIAG_SHADER_PACKAGE_MISMATCH, TN_DIAG_CAPABILITY_MISMATCH. */
TN_EXPORT tn_status_t tn_version_handshake(const tn_version_info_t *module,
                                           tn_version_info_t *engine,
                                           tn_diagnostic_t *diagnostic);

TN_EXPORT tn_status_t tn_context_create(tn_context_t **out_context, const tn_version_info_t *module,
                                        tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_context_destroy(tn_context_t *context, tn_diagnostic_t *diagnostic);

/* The handle type id of a catalog class name, or 0 when the catalog does not publish it. */
TN_EXPORT uint16_t tn_type_id(const char *name);
TN_EXPORT tn_status_t tn_object_create(tn_context_t *context, uint16_t type, tn_handle_t *out_object,
                                       tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_object_release(tn_handle_t object, tn_diagnostic_t *diagnostic);
/* For each of the count handles, how many references other engine objects hold to its object (a
 * parent, a material slot, a skeleton), 0 for an unknown handle: a language keeps its wrapper, and
 * the state on it, while the count is above zero. One call for a batch, so a safe point costs one
 * crossing. */
TN_EXPORT void tn_object_engine_references(const tn_handle_t *objects, uint32_t count, uint32_t *out_counts);

/* A value crossing the generic binding calls. One flat struct, no union: only the fields its
 * kind names are read. Strings and number arrays a call returns are owned by the context and stay
 * valid until that context's next call. */
#define TN_VALUE_NULL 0u
#define TN_VALUE_NUMBER 1u
#define TN_VALUE_BOOL 2u
#define TN_VALUE_STRING 3u
#define TN_VALUE_HANDLE 4u
#define TN_VALUE_NUMBERS 5u
#define TN_VALUE_ARRAY 6u
#define TN_VALUE_RECORD 7u
#define TN_VALUE_UNDEFINED 8u
/* A typed array as its own bytes: count elements of the type text names ("Float32Array", "Uint16Array"),
 * at bytes. A class whose constructor keeps them (BufferAttribute) copies them as they are. */
#define TN_VALUE_BYTES 9u
typedef struct tn_value {
  uint32_t kind;
  uint32_t boolean;
  double number;
  tn_handle_t handle;
  uint32_t reserved;
  const char *text;
  uint64_t count; /* bytes of text, or elements of numbers or bytes */
  /* ARRAY: count values; RECORD: count alternating string-key/value pairs. */
  union { const double *numbers; const struct tn_value *values; const void *bytes; };
} tn_value_t;

/* The generic binding calls over the engine's one registry: the same classes, methods and
 * properties the differential fixtures prove. Members are named as in three (applyMatrix4,
 * position.x, elements); an unregistered one returns TN_ERROR_UNSUPPORTED naming it. */
TN_EXPORT tn_status_t tn_construct(tn_context_t *context, const char *class_name, const tn_value_t *args,
                                   uint32_t arg_count, tn_handle_t *out_object, tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_invoke(tn_handle_t self, const char *method, const tn_value_t *args, uint32_t arg_count,
                                tn_value_t *result, tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_get(tn_handle_t self, const char *path, tn_value_t *result, tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_set(tn_handle_t self, const char *path, const tn_value_t *value, tn_diagnostic_t *diagnostic);

/* A callback a language sets on an object, which the engine runs at a defined point (PRD-531,
 * PRD-506). Today: \`onBeforeRender\`, run before the object is drawn with three's six arguments
 * (renderer, scene, camera, geometry, material, group); the renderer and the group are null, the
 * others are handles or null. \`invoke\` returns TN_OK, or writes a NUL-terminated message of at most
 * \`error_capacity\` bytes into \`error\` and returns another status when the callee threw: the engine
 * records it as a render diagnostic and goes on. \`release\` runs exactly once, when the engine drops
 * the pair: the callback is replaced, cleared with a null \`invoke\`, or its object is destroyed. */
typedef tn_status_t (*tn_object_callback_t)(void *context, const tn_value_t *args, uint32_t arg_count,
                                            char *error, uint32_t error_capacity);
typedef void (*tn_release_t)(void *context);
TN_EXPORT tn_status_t tn_set_callback(tn_handle_t self, const char *name, tn_object_callback_t invoke, void *context,
                                      tn_release_t release, tn_diagnostic_t *diagnostic);

/* Releases a diagnostic's owned string. Safe on a zeroed struct. */
TN_EXPORT void tn_diagnostic_release(tn_diagnostic_t *diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* THREENATIVE_ABI_TN_ABI_H */
`;
}

const TYPE_TABLE = path.join(
  ROOT,
  "packages",
  "runtime-native",
  "src",
  "engine",
  "abi",
  "catalog_types.inc",
);

/**
 * The ABI's type ids: one per catalog class, 1-based in catalog order (0 means "not published").
 * Reordering or removing a class changes the ids, which is a compatibility-contract change.
 */
function typeTable(catalog: ICatalog): string {
  const classes = catalog.entries.filter((entry) => entry.kind === "class");
  return [
    "// Generated by @threenative/three-native from api/catalog.json. Do not edit.",
    "// TN_CATALOG_TYPE(name, id): one per catalog class, 1-based in catalog order.",
    ...classes.map((entry, index) => `TN_CATALOG_TYPE("${entry.name}", ${index + 1})`),
    "",
  ].join("\n");
}

function generate(): void {
  const catalog = loadCatalog(ROOT);
  mkdirSync(path.dirname(DECLARATIONS), { recursive: true });
  mkdirSync(path.dirname(HEADER), { recursive: true });
  writeFileSync(DECLARATIONS, declarations(catalog));
  writeFileSync(HEADER, header(catalog));
  mkdirSync(path.dirname(TYPE_TABLE), { recursive: true });
  writeFileSync(TYPE_TABLE, typeTable(catalog));
  const supported = catalog.entries.filter((entry) => entry.status.kind === "supported").length;
  process.stdout.write(
    `TN_API_CATALOG_GENERATED: ${catalog.entries.length} entries, ${supported} supported -> ${path.relative(ROOT, DECLARATIONS)}, ${path.relative(ROOT, HEADER)}\n`,
  );
}

generate();
