/* Generated by @threenative/three-native from api/catalog.json. Do not edit.
 *
 * The binding boundary of the N03 catalog: fixed-width fields, opaque typed handles, explicit
 * buffer descriptors, callback-plus-context pairs, status codes and owned diagnostic strings. No
 * STL container and no C++ exception crosses it.
 *
 * Every code is a `#define` over a `uint32_t` typedef, never a C enum: an enum's width is the
 * compiler's choice, so its size would not be part of the contract. Values are never renumbered or
 * reused; new codes append. `TN_STATIC_ASSERT` is `_Static_assert` in C and `static_assert` in
 * C++, so every translation unit that includes this header checks the layout below.
 *
 * Reference: three 0.185.1, @types/three@0.185.3,
 * patch packages/core/patches/three@0.185.1.patch.
 */

#ifndef THREENATIVE_ABI_TN_ABI_H
#define THREENATIVE_ABI_TN_ABI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Linkage annotation; a single-translation-unit build needs none. */
#ifndef TN_EXPORT
#define TN_EXPORT
#endif

#ifdef __cplusplus
#define TN_STATIC_ASSERT(condition, message) static_assert(condition, message)
#else
#define TN_STATIC_ASSERT(condition, message) _Static_assert(condition, message)
#endif

#define TN_ENGINE_ABI_VERSION 1u
#define TN_COMPATIBILITY_CONTRACT_VERSION 1u
#define TN_SCENE_VERSION 1u
#define TN_SHADER_PACKAGE_VERSION 1u

/* FNV-1a 64 over the UTF-8 bytes of the text "tn/native/capability/v1:" followed by the names
 * of the catalog entries with status `supported`, sorted by code unit and joined with a single
 * newline, with no trailing newline. A module built against a different published surface hashes
 * differently, which is what TN_DIAG_CAPABILITY_MISMATCH reports. */
#define TN_CAPABILITY_DIGEST 0xe1b8060012c360f2ull
#define TN_CAPABILITY_COUNT 126u

typedef uint32_t tn_status_t;

#define TN_OK 0u /* The call succeeded and carries no diagnostic. */
#define TN_ERROR_INVALID_ARGUMENT 1u /* A descriptor, length, stride or scalar type was not usable. */
#define TN_ERROR_INVALID_HANDLE 2u /* The handle's type, context or generation did not resolve. */
#define TN_ERROR_STALE_HANDLE 3u /* The slot was reclaimed and its generation no longer matches. */
#define TN_ERROR_WRONG_TYPE 4u /* The handle resolved to a different catalog type. */
#define TN_ERROR_OUT_OF_MEMORY 5u /* The engine could not satisfy the request. */
#define TN_ERROR_UNSUPPORTED 6u /* The catalog marks this operation unsupported; see its diagnostic code. */
#define TN_ERROR_VERSION_MISMATCH 7u /* A version number or the capability digest is not the engine's own. */
#define TN_ERROR_INVALID_STATE 8u /* The object is not in a state where the call is defined. */
#define TN_ERROR_BUFFER_NOT_READY 9u /* The buffer is still owned by the engine for this submission. */

/* The named reasons a version handshake failed, carried in tn_diagnostic_t::code while the status
 * stays TN_ERROR_VERSION_MISMATCH. New codes append. */
#define TN_DIAG_ENGINE_ABI_MISMATCH 1001u /* engine_abi differs from the engine's own. */
#define TN_DIAG_CONTRACT_MISMATCH 1002u /* compatibility_contract differs from the engine's own. */
#define TN_DIAG_SCENE_MISMATCH 1003u /* scene differs from the engine's own. */
#define TN_DIAG_SHADER_PACKAGE_MISMATCH 1004u /* shader_package differs from the engine's own. */
#define TN_DIAG_CAPABILITY_MISMATCH 1005u /* capability_count or capability_digest differs from the engine's own. */

/* An opaque typed handle. `context` separates independent handle tables and `generation` catches a
 * reclaimed slot, so a stale handle returns a status code instead of aliasing live state. */
typedef struct tn_handle {
  uint16_t type;
  uint16_t context;
  uint32_t index;
  uint32_t generation;
} tn_handle_t;

TN_STATIC_ASSERT(sizeof(tn_handle_t) == 12, "tn_handle_t must stay 12 bytes: 2 + 2 + 4 + 4.");
TN_STATIC_ASSERT(offsetof(tn_handle_t, type) == 0 && offsetof(tn_handle_t, context) == 2 &&
                     offsetof(tn_handle_t, index) == 4 && offsetof(tn_handle_t, generation) == 8,
                 "tn_handle_t must keep this field order and no padding holes.");

/* A diagnostic the caller owns: release it with tn_diagnostic_release, never with free(). Pass a
 * zeroed struct the first time; every call that takes one releases the message it held before
 * writing, so one diagnostic can be reused across calls without leaking. */
typedef struct tn_diagnostic {
  char *message;
  uint32_t code;
} tn_diagnostic_t;

typedef uint32_t tn_scalar_type_t;

#define TN_SCALAR_F32 0u /* IEEE-754 binary32. */
#define TN_SCALAR_I32 1u /* Signed 32-bit integer. */
#define TN_SCALAR_U32 2u /* Unsigned 32-bit integer. */
#define TN_SCALAR_U8 3u /* Unsigned 8-bit integer. */
#define TN_SCALAR_U16 4u /* Unsigned 16-bit integer. */
#define TN_SCALAR_I16 5u /* Signed 16-bit integer. */

typedef uint32_t tn_buffer_owner_t;

#define TN_BUFFER_OWNER_ENGINE 0u /* The engine owns the storage for the lifetime of the lease. */
#define TN_BUFFER_OWNER_CALLER 1u /* The caller owns the storage and keeps it alive until the engine is done with it. */

typedef uint32_t tn_buffer_mutability_t;

#define TN_BUFFER_READ_ONLY 0u /* The engine only reads through the descriptor. */
#define TN_BUFFER_READ_WRITE 1u /* The engine writes through the descriptor. */

/* Every buffer crossing the ABI states its owner, length, stride, scalar type and mutability.
 * Ownership and lease rules are PRD-504; `length` counts elements, never bytes. */
typedef struct tn_buffer_desc {
  void *data;
  uint64_t length;
  uint64_t stride;
  tn_scalar_type_t scalar_type;
  tn_buffer_owner_t owner;
  tn_buffer_mutability_t mutability;
  /* Bumped by the engine on every write, so a retained view can prove it is current. */
  uint32_t version;
} tn_buffer_desc_t;

TN_STATIC_ASSERT(sizeof(tn_buffer_desc_t) == 40,
                 "tn_buffer_desc_t must stay 40 bytes: 8 + 8 + 8 + 4 + 4 + 4 + 4.");
TN_STATIC_ASSERT(offsetof(tn_buffer_desc_t, data) == 0 && offsetof(tn_buffer_desc_t, length) == 8 &&
                     offsetof(tn_buffer_desc_t, stride) == 16 &&
                     offsetof(tn_buffer_desc_t, scalar_type) == 24 &&
                     offsetof(tn_buffer_desc_t, owner) == 28 &&
                     offsetof(tn_buffer_desc_t, mutability) == 32 &&
                     offsetof(tn_buffer_desc_t, version) == 36,
                 "tn_buffer_desc_t must keep this field order and no padding holes.");

/* A callback plus the context it runs with. The pair crosses as one value; a bare function pointer
 * would lose the wrapper that owns the capture. */
typedef void (*tn_callback_t)(void *context, const tn_diagnostic_t *diagnostic);

/* The 64-bit digest comes first so nothing precedes it, and `reserved` names the four tail bytes
 * the 8-byte alignment would otherwise insert: the struct has no implicit padding. */
typedef struct tn_version_info {
  uint64_t capability_digest;
  uint32_t engine_abi;
  uint32_t compatibility_contract;
  uint32_t scene;
  uint32_t shader_package;
  uint32_t capability_count;
  uint32_t reserved;
} tn_version_info_t;

TN_STATIC_ASSERT(sizeof(tn_version_info_t) == 32,
                 "tn_version_info_t must stay 32 bytes: 8 + 4 + 4 + 4 + 4 + 4 + 4.");
TN_STATIC_ASSERT(offsetof(tn_version_info_t, capability_digest) == 0 &&
                     offsetof(tn_version_info_t, engine_abi) == 8 &&
                     offsetof(tn_version_info_t, compatibility_contract) == 12 &&
                     offsetof(tn_version_info_t, scene) == 16 &&
                     offsetof(tn_version_info_t, shader_package) == 20 &&
                     offsetof(tn_version_info_t, capability_count) == 24 &&
                     offsetof(tn_version_info_t, reserved) == 28,
                 "tn_version_info_t must keep this field order and no padding holes.");

typedef struct tn_context tn_context_t;

/* The engine's own versions, capability count and capability digest. */
TN_EXPORT tn_version_info_t tn_engine_version(void);

/* Rejects a module built against a different engine ABI, compatibility contract, scene, shader
 * package or capability set before any game code runs. On mismatch it returns
 * TN_ERROR_VERSION_MISMATCH, fills `engine` when it is non-NULL, and sets `diagnostic->code` to the
 * first differing field in this order: TN_DIAG_ENGINE_ABI_MISMATCH, TN_DIAG_CONTRACT_MISMATCH,
 * TN_DIAG_SCENE_MISMATCH, TN_DIAG_SHADER_PACKAGE_MISMATCH, TN_DIAG_CAPABILITY_MISMATCH. */
TN_EXPORT tn_status_t tn_version_handshake(const tn_version_info_t *module,
                                           tn_version_info_t *engine,
                                           tn_diagnostic_t *diagnostic);

TN_EXPORT tn_status_t tn_context_create(tn_context_t **out_context, const tn_version_info_t *module,
                                        tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_context_destroy(tn_context_t *context, tn_diagnostic_t *diagnostic);

/* The handle type id of a catalog class name, or 0 when the catalog does not publish it. */
TN_EXPORT uint16_t tn_type_id(const char *name);
TN_EXPORT tn_status_t tn_object_create(tn_context_t *context, uint16_t type, tn_handle_t *out_object,
                                       tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_object_release(tn_handle_t object, tn_diagnostic_t *diagnostic);
/* For each of the count handles, how many references other engine objects hold to its object (a
 * parent, a material slot, a skeleton), 0 for an unknown handle: a language keeps its wrapper, and
 * the state on it, while the count is above zero. One call for a batch, so a safe point costs one
 * crossing. */
TN_EXPORT void tn_object_engine_references(const tn_handle_t *objects, uint32_t count, uint32_t *out_counts);

/* A value crossing the generic binding calls. One flat struct, no union: only the fields its
 * kind names are read. Strings and number arrays a call returns are owned by the context and stay
 * valid until that context's next call. */
#define TN_VALUE_NULL 0u
#define TN_VALUE_NUMBER 1u
#define TN_VALUE_BOOL 2u
#define TN_VALUE_STRING 3u
#define TN_VALUE_HANDLE 4u
#define TN_VALUE_NUMBERS 5u
#define TN_VALUE_ARRAY 6u
#define TN_VALUE_RECORD 7u
#define TN_VALUE_UNDEFINED 8u
/* A typed array as its own bytes: count elements of the type text names ("Float32Array", "Uint16Array"),
 * at bytes. A class whose constructor keeps them (BufferAttribute) copies them as they are. */
#define TN_VALUE_BYTES 9u
typedef struct tn_value {
  uint32_t kind;
  uint32_t boolean;
  double number;
  tn_handle_t handle;
  uint32_t reserved;
  const char *text;
  uint64_t count; /* bytes of text, or elements of numbers or bytes */
  /* ARRAY: count values; RECORD: count alternating string-key/value pairs. */
  union { const double *numbers; const struct tn_value *values; const void *bytes; };
} tn_value_t;

/* The generic binding calls over the engine's one registry: the same classes, methods and
 * properties the differential fixtures prove. Members are named as in three (applyMatrix4,
 * position.x, elements); an unregistered one returns TN_ERROR_UNSUPPORTED naming it. */
TN_EXPORT tn_status_t tn_construct(tn_context_t *context, const char *class_name, const tn_value_t *args,
                                   uint32_t arg_count, tn_handle_t *out_object, tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_invoke(tn_handle_t self, const char *method, const tn_value_t *args, uint32_t arg_count,
                                tn_value_t *result, tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_get(tn_handle_t self, const char *path, tn_value_t *result, tn_diagnostic_t *diagnostic);
TN_EXPORT tn_status_t tn_set(tn_handle_t self, const char *path, const tn_value_t *value, tn_diagnostic_t *diagnostic);

/* A callback a language sets on an object, which the engine runs at a defined point (PRD-531,
 * PRD-506). Today: `onBeforeRender`, run before the object is drawn with three's six arguments
 * (renderer, scene, camera, geometry, material, group); the renderer and the group are null, the
 * others are handles or null. `invoke` returns TN_OK, or writes a NUL-terminated message of at most
 * `error_capacity` bytes into `error` and returns another status when the callee threw: the engine
 * records it as a render diagnostic and goes on. `release` runs exactly once, when the engine drops
 * the pair: the callback is replaced, cleared with a null `invoke`, or its object is destroyed. */
typedef tn_status_t (*tn_object_callback_t)(void *context, const tn_value_t *args, uint32_t arg_count,
                                            char *error, uint32_t error_capacity);
typedef void (*tn_release_t)(void *context);
TN_EXPORT tn_status_t tn_set_callback(tn_handle_t self, const char *name, tn_object_callback_t invoke, void *context,
                                      tn_release_t release, tn_diagnostic_t *diagnostic);

/* Releases a diagnostic's owned string. Safe on a zeroed struct. */
TN_EXPORT void tn_diagnostic_release(tn_diagnostic_t *diagnostic);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* THREENATIVE_ABI_TN_ABI_H */
